//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinApp.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int insertRecord(string pomiar, string data_pomiaru);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<int> insertRecordAsync(string pomiar, string data_pomiaru);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WinApp.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WinApp.ServiceReference1.WebServiceSoap>, WinApp.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int insertRecord(string pomiar, string data_pomiaru) {
            return base.Channel.insertRecord(pomiar, data_pomiaru);
        }
        
        public System.Threading.Tasks.Task<int> insertRecordAsync(string pomiar, string data_pomiaru) {
            return base.Channel.insertRecordAsync(pomiar, data_pomiaru);
        }
        
        public System.Data.DataTable getData() {
            return base.Channel.getData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getDataAsync() {
            return base.Channel.getDataAsync();
        }
    }
}
